version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management UI port
    networks:
      - my-network

  invoicing-service:
    container_name: invoicing-service
    image: invoicing-service
    build:
      context: invoicing-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - my-network
      
  payment-service:
    container_name: payment-service
    image: payment-service
    build:
      context: payment-service
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - rabbitmq
    networks:
      - my-network
    #deploy:
    #  replicas: 4

  invoicing-web:
    container_name: invoicing-web
    image: invoicing-web
    build:
      context: invoicing-web
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "5173:80"
    depends_on:
      - invoicing-service
    networks:
      - my-network

networks:
    my-network:
      driver: bridge